Repository 5MYBAB/itta-bab-backend, pull requests merged in 2024-10, with the labels that each got.

#135 fix: security 일부 수정
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  src/main/java/com/fivemybab/ittabab/security/handler/LoginSuccessHandler.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
Labels: fix

#136 feat: 메뉴 카테고리 기능 구현 및 레포지토리 리팩토링
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreMenuCategoryController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreMenuCategoryDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreMenuCategoryInfoDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/UpdateStoreMenuCategoryDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreFavoriteRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreMenuCategoryRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreMenuRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreOrderMenuRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreReviewRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuCategoryService.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/StoreMenuCategory.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreMenuCategoryQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreMenuCategoryMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreMenuCategoryQueryService.java
  src/main/resources/mapper/store/StoreMenuCategoryMapper.xml
Labels: enhancement, refactor

#138 chore: group 컨트롤러 테스트 제거
  src/test/java/com/fivemybab/ittabab/group/command/application/controller/GroupCommentCommandControllerTest.java
  src/test/java/com/fivemybab/ittabab/group/command/application/controller/GroupControllerTest.java
Labels: refactor

#139 refactor: 가게 조회 쿼리 리팩토링
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/Store.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/StoreStatus.java
  src/main/resources/mapper/store/StoreMapper.xml
  src/main/resources/mapper/store/StoreReviewMapper.xml
Labels: refactor

#140 feat: #69 일정 리팩토링, test코드 추가
  src/main/java/com/fivemybab/ittabab/schedule/command/application/controller/ScheduleCommandController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/service/ScheduleCommandService.java
  src/test/java/com/fivemybab/ittabab/schedule/command/service/ScheduleServiceTest.java
  src/test/java/com/fivemybab/ittabab/schedule/query/service/ScheduleQueryServiceTest.java
Labels: enhancement, refactor

#141 feat: 문의 리팩토링, test 코드 추가
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/controller/InquiryCommandController.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/service/InquiryCommandService.java
  src/main/java/com/fivemybab/ittabab/inquiry/query/controller/InquiryQueryController.java
  src/main/java/com/fivemybab/ittabab/inquiry/query/service/InquiryQueryService.java
  src/test/java/com/fivemybab/ittabab/inquiry/command/application/service/InquiryCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/inquiry/query/service/InquiryQueryServiceTest.java
Labels: enhancement, refactor

#143 feat: 회원 관련 테스트 추가
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/FriendCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/UpdateFriendRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/FriendCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/Friend.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/repository/FriendRepository.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/FriendQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/NotificationQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/dto/NotificationDto.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/FriendMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/NotificationMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/service/BootCampQueryService.java
  src/main/java/com/fivemybab/ittabab/user/query/service/FriendQueryService.java
  src/main/java/com/fivemybab/ittabab/user/query/service/NotificationQueryService.java
  src/main/resources/mapper/user/FriendMapper.xml
  src/main/resources/mapper/user/NotificationMapper.xml
  src/test/java/com/fivemybab/ittabab/user/command/application/service/BootCampCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/command/application/service/CourseCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/command/application/service/FriendCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/command/application/service/NotificationCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/command/application/service/UserCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/query/service/BootCampQueryServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/query/service/CourseQueryServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/query/service/FriendQueryServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/query/service/NotificationQueryServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/query/service/UserQueryServiceTest.java
Labels: enhancement

#144 feat: 좋아요 기능 리팩토링, test 코드 추가
  src/main/java/com/fivemybab/ittabab/good/command/application/controller/GoodCommandController.java
  src/main/java/com/fivemybab/ittabab/good/command/application/service/GoodCommandService.java
  src/main/java/com/fivemybab/ittabab/report/command/domain/aggregate/Target.java
  src/test/java/com/fivemybab/ittabab/good/command/application/service/GoodCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/good/query/service/GoodQueryServiceTest.java
Labels: enhancement, refactor

#145 feat: 예외 핸들러 추가
  src/main/java/com/fivemybab/ittabab/exception/ErrorResponse.java
  src/main/java/com/fivemybab/ittabab/exception/GlobalExceptionHandler.java
  src/main/java/com/fivemybab/ittabab/exception/ServerInternalException.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/FriendCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/FriendCommandService.java
Labels: enhancement

#147 refactor: #146 예외처리 수정
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/service/InquiryCommandService.java
  src/main/java/com/fivemybab/ittabab/report/command/application/service/ReportService.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/service/ScheduleCommandService.java
Labels: refactor

#149 feat: board 테스트 추가
  src/main/java/com/fivemybab/ittabab/board/command/application/dto/CreatePostCommentDto.java
  src/main/java/com/fivemybab/ittabab/board/command/application/dto/CreatePostDto.java
  src/main/java/com/fivemybab/ittabab/board/command/application/service/PostCommandService.java
  src/main/java/com/fivemybab/ittabab/board/command/application/service/PostCommentCommandService.java
  src/test/java/com/fivemybab/ittabab/board/command/application/service/PostCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/board/command/application/service/PostCommentCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/board/query/service/PostCommentQueryServiceTest.java
  src/test/java/com/fivemybab/ittabab/board/query/service/PostQueryServiceTest.java
Labels: enhancement

#150 feat: 가게 인기순으로 조회 기능 구현
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StorePopularInfoDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/Store.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreQueryService.java
  src/main/resources/mapper/store/StoreMapper.xml
  src/main/resources/mapper/store/StoreMenuMapper.xml
Labels: enhancement

#152 feat: #151 사진 test 코드 구현
  src/test/java/com/fivemybab/ittabab/picture/command/application/service/PictureCommandServiceTest.java
Labels: enhancement

#153 fix: security 오류 수정
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  src/main/java/com/fivemybab/ittabab/security/handler/LoginSuccessHandler.java
  src/main/java/com/fivemybab/ittabab/security/util/CustomUserDetailsService.java
Labels: fix

#154 feat: 메뉴 인기순으로 조회 기능 추가
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StorePopularMenuInfoDto.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreMenuQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreMenuMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreMenuQueryService.java
  src/main/resources/mapper/store/StoreMenuMapper.xml
Labels: enhancement

#155 feat: controller @operation 어노테이션 내용 추가
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostQueryController.java
Labels: enhancement

#158 feat: 이메일 인증 기능 구현
  build.gradle
  src/main/java/com/fivemybab/ittabab/config/MailConfig.java
  src/main/java/com/fivemybab/ittabab/config/RedisConfig.java
  src/main/java/com/fivemybab/ittabab/config/redis/MailService.java
  src/main/java/com/fivemybab/ittabab/config/redis/MailServiceImpl.java
  src/main/java/com/fivemybab/ittabab/config/redis/RedisService.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/CreateUserRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/MailRequestDto.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/repository/UserRepository.java
  src/main/resources/application.yml
Labels: enhancement

#156 feat: 특정 가게 리뷰 조회 쿼리 구현 및 리팩토링
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreFavoriteController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/Store.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreFavoriteQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreMenuQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreReviewQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreReviewMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreReviewQueryService.java
  src/main/resources/mapper/store/StoreMapper.xml
  src/main/resources/mapper/store/StoreMenuMapper.xml
  src/main/resources/mapper/store/StoreReviewMapper.xml
Labels: enhancement, refactor

#159 fix: yml 수정
  src/main/java/com/fivemybab/ittabab/config/MailConfig.java
  src/main/java/com/fivemybab/ittabab/config/redis/MailServiceImpl.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
  src/main/resources/application.yml
Labels: fix

#162 feat: 채팅방 생성 및 전송 기능 개발 및 rest-api 설명 추가
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupInfoCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandService.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/ChatRoomStatus.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/GroupInfo.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupInfoQueryController.java
  src/main/java/com/fivemybab/ittabab/group/query/dto/GroupInfoDto.java
  src/main/java/com/fivemybab/ittabab/group/query/dto/RequestChatDto.java
  src/main/resources/application.yml
  src/main/resources/mapper/group/GroupCommentMapper.xml
  src/main/resources/mapper/group/GroupInfoMapper.xml
  src/test/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandServiceTest.java
Labels: enhancement

#161 refact: security 접근 권한 설정(store 제외)
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostQueryController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupInfoCommandController.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/controller/InquiryCommandController.java
  src/main/java/com/fivemybab/ittabab/report/command/application/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/query/controller/ReportQueryController.java
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/UserQueryController.java
Labels: refactor

#160 feat: 특정 유저 주문 메뉴 전체 조회
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreUserOrderMenuInfoDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreOrderMenuQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreOrderMenuMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreOrderMenuQueryService.java
  src/main/resources/mapper/store/StoreOrderMenuMapper.xml
  src/test/java/com/fivemybab/ittabab/store/command/application/service/StoreServiceTest.java
Labels: enhancement, refactor

#164 fix: 병합 오류 수정
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandService.java
Labels: fix

#166 docs: db ddl 추가
  db/itta_bab_DDL.sql
Labels: documentation

#167 fix: security 오류 고침
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
Labels: fix

#168 fix: security 수정
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
Labels: fix

#169 fix: security 수정
  src/main/java/com/fivemybab/ittabab/security/util/CustomUserDetailsService.java
  src/main/java/com/fivemybab/ittabab/security/util/JwtUtil.java
Labels: fix

#171 feat: 모임 채팅 rest-api 개선
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupInfoCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandService.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/ChatRoomStatus.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/GroupInfo.java
Labels: enhancement

#172 feat: 로그인한 사용자만 가게 CRUD 가능하도록 기능 수정
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/UpdateStoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/test/java/com/fivemybab/ittabab/store/command/application/service/StoreServiceTest.java
Labels: enhancement, refactor

#175 feat: dummy data
  db/DummyData.sql
Labels: enhancement

#176 fix: swagger test 오류 고침
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/controller/InquiryCommandController.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/dto/InquiryAnswerResponse.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/dto/InquiryQuestionResponse.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/service/InquiryCommandService.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/domain/aggregate/Inquiry.java
  src/main/java/com/fivemybab/ittabab/report/command/application/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/command/application/dto/ResolveReportRequest.java
  src/main/java/com/fivemybab/ittabab/report/command/application/service/ReportService.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/controller/ScheduleCommandController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/dto/ScheduleCreateRequire.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/service/ScheduleCommandService.java
  src/main/java/com/fivemybab/ittabab/schedule/command/domain/aggregate/ScheduleInfo.java
  src/test/java/com/fivemybab/ittabab/inquiry/command/application/service/InquiryCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/report/command/application/service/ReportServiceTest.java
  src/test/java/com/fivemybab/ittabab/schedule/command/service/ScheduleServiceTest.java
Labels: fix

#174 가게 및 가게 리뷰 생성 및 수정 기능 구현(예외처리 완료)
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreReviewController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreReviewDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/UpdateStoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/UpdateStoreReviewDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreReviewRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreReviewService.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/Store.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/StoreReview.java
  src/test/java/com/fivemybab/ittabab/store/command/application/service/StoreServiceTest.java
Labels: enhancement, refactor

#177 feat: 가게 즐겨찾기 등록 추가(삭제는 오류 발생)
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreFavoriteController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreMenuCategoryController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreMenuController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreFavoriteDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreFavoriteRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreMenuCategoryRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreFavoriteService.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuCategoryService.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuService.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/StoreFavorite.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreFavoriteQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreFavoriteMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreFavoriteQueryService.java
  src/main/resources/mapper/store/StoreFavoriteMapper.xml
Labels: enhancement

#178 fix: 좋아요 기능 오류 수정
  src/main/java/com/fivemybab/ittabab/good/query/controller/GoodQueryController.java
  src/main/java/com/fivemybab/ittabab/good/query/dto/CountGoodRequest.java
  src/main/java/com/fivemybab/ittabab/good/query/mapper/GoodMapper.java
  src/main/java/com/fivemybab/ittabab/good/query/service/GoodQueryService.java
  src/test/java/com/fivemybab/ittabab/good/query/service/GoodQueryServiceTest.java
Labels: fix

#179 feat: 위치 인증 후 회원가입 구현
  build.gradle
  db/itta_bab_DDL.sql
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/CreateBootCampRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/UpdateBootCampRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/BootCampCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/BootCamp.java
  src/main/java/com/fivemybab/ittabab/user/query/dto/BootCampDto.java
  src/main/resources/application.yml
  src/main/resources/mapper/user/BootCampMapper.xml
Labels: enhancement

#180 fix: friend 일부 수정
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/FriendCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/FriendRequestDTO.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/FriendCommandService.java
  src/test/java/com/fivemybab/ittabab/user/command/application/service/FriendCommandServiceTest.java
Labels: fix

#182 fix: 주문 메뉴(order_menu) 테이블 DDL 및 더미 데이터 수정 반영
  db/DummyData.sql
  db/itta_bab_DDL.sql
Labels: fix

#183 fix: 일정 코드 수정
  src/main/java/com/fivemybab/ittabab/schedule/command/application/controller/ScheduleCommandController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/service/ScheduleCommandService.java
  src/main/java/com/fivemybab/ittabab/schedule/command/domain/repository/ScheduleRepository.java
Labels: fix

#186 refactor: 모임 코드 리펙토링
  http/security-test.http
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupInfoCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandService.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupInfoQueryController.java
  src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupInfoMapper.java
  src/main/java/com/fivemybab/ittabab/group/query/service/GroupInfoQueryService.java
  src/main/resources/mapper/group/GroupInfoMapper.xml
  src/test/java/com/fivemybab/ittabab/group/command/application/service/GroupCommentCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/group/query/service/GroupInfoQueryServiceTest.java
  src/test/java/com/fivemybab/ittabab/user/command/application/service/BootCampCommandServiceTest.java
Labels: refactor

#187 feat: 가게 삭제, 메뉴 삭제, 메뉴 카테고리 삭제, 주문 메뉴 삭제 관리자 기능 구현
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreMenuCategoryController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreMenuController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreOrderMenuController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreFavoriteRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreMenuRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreOrderMenuRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreReviewRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuCategoryService.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreOrderMenuService.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/test/java/com/fivemybab/ittabab/store/command/application/service/StoreServiceTest.java
Labels: fix

#184 feat: board 조회부분 수정
  build.gradle
  http/security-test.http
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/dto/CreatePostCommentDto.java
  src/main/java/com/fivemybab/ittabab/board/command/application/service/PostCommentCommandService.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/aggregate/PostComment.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/dto/PostQueryDto.java
  src/main/java/com/fivemybab/ittabab/board/query/mapper/PostQueryMapper.java
  src/main/java/com/fivemybab/ittabab/board/query/service/PostQueryService.java
  src/main/java/com/fivemybab/ittabab/security/util/CustomUserDetails.java
  src/main/java/com/fivemybab/ittabab/security/util/CustomUserDetailsService.java
  src/main/resources/application.yml
  src/main/resources/mapper/board/PostMapper.xml
  src/test/java/com/fivemybab/ittabab/board/query/service/PostQueryServiceTest.java
  src/test/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/group/query/service/GroupInfoQueryServiceTest.java
Labels: enhancement

#189 fix: 모임 버그 수정
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupInfoCommandController.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupInfoQueryController.java
Labels: fix

#190 fix: 관리자 메뉴 삭제 기능
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreOrderMenuRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuService.java
Labels: fix

#192 docs: readme 수정
  README.md
  readmepic/primary/chat-test.png
  readmepic/primary/chat.png
Labels: documentation

#193 fix: user 도메인 일부 수정
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/FriendCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/Friend.java
Labels: fix

#195 docs: 형식 수정
  README.md
Labels: documentation

#199 refactor: 디렉토리 구조 수정
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreFavoriteService.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuCategoryService.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuService.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreOrderMenuService.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreReviewService.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreFavoriteRepository.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreMenuCategoryRepository.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreMenuRepository.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreOrderMenuRepository.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreRepository.java
  MSA/ittabab-store-service/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreReviewRepository.java
  Monolithic/src/main/java/com/fivemybab/ittabab/report/command/application/service/ReportService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreFavoriteService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuCategoryService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreOrderMenuService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreReviewService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreFavoriteRepository.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreMenuCategoryRepository.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreMenuRepository.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreOrderMenuRepository.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreRepository.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/domain/repository/StoreReviewRepository.java
Labels: refactor

#200 docs: 회고록 추가
  README.md
  readmepic/1.png
  readmepic/2.png
Labels: documentation

#201 feat: 모임 카테고리 조회 기능 개발
  Monolithic/src/main/java/com/fivemybab/ittabab/group/query/controller/GroupCategoryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupCategoryMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/group/query/service/GroupCategoryService.java
  Monolithic/src/main/resources/mapper/group/GroupCategoryMapper.xml
Labels: enhancement

#202 fix: schedule 날짜 오류 고침
  Monolithic/src/main/java/com/fivemybab/ittabab/schedule/command/application/controller/ScheduleCommandController.java
Labels: fix

#203 feat: 게시글 작성 관련 기능 개발
  Monolithic/src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommandController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/command/application/dto/CreatePostDto.java
Labels: enhancement

#205 feat: 문의 답변 상세 구현
  Monolithic/src/main/java/com/fivemybab/ittabab/inquiry/query/controller/InquiryQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/inquiry/query/dto/InquiryDto.java
  Monolithic/src/main/java/com/fivemybab/ittabab/inquiry/query/mapper/InquiryMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/inquiry/query/service/InquiryQueryService.java
  Monolithic/src/main/resources/mapper/inquiry/InquiryMapper.xml
Labels: enhancement

#206 feat: 참여중인 활성화된 모임 조회 기능 개발
  Monolithic/http/security-test.http
  Monolithic/src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupInfoCommandController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/group/query/controller/GroupInfoQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/group/query/dto/RequestGroupUser.java
  Monolithic/src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupInfoMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/group/query/service/GroupInfoQueryService.java
  Monolithic/src/main/resources/mapper/group/GroupInfoMapper.xml
Labels: enhancement

#207 feat: 신고에 GROUP 추가
  Monolithic/src/main/java/com/fivemybab/ittabab/report/command/application/service/ReportService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/report/command/domain/aggregate/Target.java
Labels: enhancement

#208 feat: 아이디 찾기, 비밀번호 찾기 api 구현
  Monolithic/src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  Monolithic/src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/user/query/controller/UserQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/user/query/mapper/UserMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/user/query/service/UserQueryService.java
  Monolithic/src/main/resources/mapper/user/UserMapper.xml
Labels: enhancement

#210 feat: board 누락 기능 구현
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/controller/PostCommentQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/controller/PostQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/dto/PostCommentResponse.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/mapper/PostCommentQueryMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/mapper/PostQueryMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/service/PostCommentQueryService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/service/PostQueryService.java
  Monolithic/src/main/resources/mapper/board/PostCommentMapper.xml
  Monolithic/src/main/resources/mapper/board/PostMapper.xml
Labels: enhancement, fix

#211 feat: 마이페이지 api 구현
  Monolithic/db/DummyData.sql
  Monolithic/src/main/java/com/fivemybab/ittabab/board/command/application/dto/CreatePostCommentDto.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/controller/PostCommentQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/controller/PostQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/dto/MyCommentResponse.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/dto/MyPostResponse.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/mapper/PostCommentQueryMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/mapper/PostQueryMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/service/PostCommentQueryService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/service/PostQueryService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/inquiry/query/controller/InquiryQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/report/query/controller/ReportQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/report/query/mapper/ReportMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/report/query/service/ReportQueryService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreFavoriteInfoDto.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/query/controller/StoreReviewQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/query/dto/MyReviewResponse.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreReviewMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/store/query/service/StoreReviewQueryService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/user/query/controller/FriendQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/user/query/dto/FriendResponse.java
  Monolithic/src/main/java/com/fivemybab/ittabab/user/query/mapper/FriendMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/user/query/service/FriendQueryService.java
  Monolithic/src/main/resources/mapper/board/PostCommentMapper.xml
  Monolithic/src/main/resources/mapper/board/PostMapper.xml
  Monolithic/src/main/resources/mapper/report/ReportMapper.xml
  Monolithic/src/main/resources/mapper/store/StoreFavoriteMapper.xml
  Monolithic/src/main/resources/mapper/store/StoreReviewMapper.xml
  Monolithic/src/main/resources/mapper/user/FriendMapper.xml
  Monolithic/src/test/java/com/fivemybab/ittabab/user/query/service/FriendQueryServiceTest.java
Labels: enhancement

#212 feat: board 기능 추가
  Monolithic/src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommentCommandController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/command/application/dto/CreatePostCommentDto.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/command/application/dto/PostCommentResponseDto.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/command/application/service/PostCommentCommandService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/command/domain/aggregate/PostComment.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/controller/PostCommentQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/controller/PostQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/mapper/PostCommentQueryMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/mapper/PostQueryMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/service/PostCommentQueryService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/board/query/service/PostQueryService.java
  Monolithic/src/main/resources/mapper/board/PostCommentMapper.xml
  Monolithic/src/main/resources/mapper/board/PostMapper.xml
Labels: enhancement

#213 fix: storeQuery문 경로 수정
  Monolithic/src/main/java/com/fivemybab/ittabab/store/query/controller/StoreReviewQueryController.java
Labels: fix

#214 fix: 좋아요 기능 수정
  Monolithic/src/main/java/com/fivemybab/ittabab/good/command/application/controller/GoodCommandController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/good/command/application/dto/GoodDto.java
  Monolithic/src/main/java/com/fivemybab/ittabab/good/command/application/service/GoodCommandService.java
  Monolithic/src/main/java/com/fivemybab/ittabab/good/command/domain/repository/GoodRepository.java
  Monolithic/src/main/java/com/fivemybab/ittabab/good/query/controller/GoodQueryController.java
  Monolithic/src/main/java/com/fivemybab/ittabab/good/query/dto/IsLikedResponse.java
  Monolithic/src/main/java/com/fivemybab/ittabab/good/query/mapper/GoodMapper.java
  Monolithic/src/main/java/com/fivemybab/ittabab/good/query/service/GoodQueryService.java
  Monolithic/src/main/resources/mapper/good/GoodMapper.xml
  Monolithic/src/test/java/com/fivemybab/ittabab/good/command/application/service/GoodCommandServiceTest.java
Labels: enhancement, fix
