Repository 5MYBAB/itta-bab-backend, pull requests merged in 2024-09, with the labels that each got.

#11 feat: #1,#2,#3, #4 일정 관리
  src/main/java/com/fivemybab/ittabab/member/command/controller/MemberCommandController.java
  src/main/java/com/fivemybab/ittabab/member/command/dto/MemberDTO.java
  src/main/java/com/fivemybab/ittabab/member/command/entity/MemberInfo.java
  src/main/java/com/fivemybab/ittabab/member/command/repository/MemberCommandRepository.java
  src/main/java/com/fivemybab/ittabab/member/command/service/MemberCommandService.java
  src/main/java/com/fivemybab/ittabab/member/query/controller/MemberQueryController.java
  src/main/java/com/fivemybab/ittabab/member/query/mapper/MemberMapper.java
  src/main/java/com/fivemybab/ittabab/member/query/service/MemberQueryService.java
  src/main/java/com/fivemybab/ittabab/schedule/command/controller/ScheduleController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/dto/ScheduleDTO.java
  src/main/java/com/fivemybab/ittabab/schedule/command/entity/ScheduleInfo.java
  src/main/java/com/fivemybab/ittabab/schedule/command/repository/ScheduleRepository.java
  src/main/java/com/fivemybab/ittabab/schedule/command/service/ScheduleService.java
  src/main/resources/templates/schedule/delete.html
  src/main/resources/templates/schedule/list.html
  src/main/resources/templates/schedule/modify.html
  src/main/resources/templates/schedule/regist.html
  src/test/java/com/fivemybab/ittabab/schedule/command/service/ScheduleServiceTest.java
Labels: enhancement

#13 feat: member 기능 구현
  src/main/java/com/fivemybab/ittabab/member/command/controller/MemberCommandController.java
  src/main/java/com/fivemybab/ittabab/member/command/dto/MemberDTO.java
  src/main/java/com/fivemybab/ittabab/member/command/entity/MemberInfo.java
  src/main/java/com/fivemybab/ittabab/member/command/repository/MemberCommandRepository.java
  src/main/java/com/fivemybab/ittabab/member/command/service/MemberCommandService.java
  src/main/java/com/fivemybab/ittabab/member/query/controller/MemberQueryController.java
  src/main/java/com/fivemybab/ittabab/member/query/mapper/MemberMapper.java
  src/main/java/com/fivemybab/ittabab/member/query/service/MemberQueryService.java
  src/main/resources/com/fivemybab/ittabab/member/query/mapper/MemberMapper.xml
Labels: enhancement

#14 feat: report 도메인 엔티티 구현
  src/main/java/com/fivemybab/ittabab/report/command/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/command/dto/ReportDTO.java
  src/main/java/com/fivemybab/ittabab/report/command/entity/ReportInfo.java
  src/main/java/com/fivemybab/ittabab/report/command/repository/ReportRepository.java
  src/main/java/com/fivemybab/ittabab/report/command/service/ReportService.java
Labels: enhancement

#15 feat: board 도메인 엔티티 구현
  src/main/java/com/fivemybab/ittabab/board/command/entity/Post.java
  src/main/java/com/fivemybab/ittabab/board/command/entity/PostComment.java
Labels: enhancement

#21 feat: store 도메인 entity 및 dto 구현
  src/main/java/com/fivemybab/ittabab/store/command/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/FavoriteDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/MenuCategoryDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/MenuDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/OrderMenuDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/ReviewDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/StoreDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/StoreStatus.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/Favorite.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/Menu.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/MenuCategory.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/OrderMenu.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/Review.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/Store.java
  src/main/java/com/fivemybab/ittabab/store/command/repository/StoreRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/service/StoreService.java
Labels: enhancement

#16 feat: entity & dto 생성
  .gitignore
  src/main/java/com/fivemybab/ittabab/group/command/dto/GroupCategoryDTO.java
  src/main/java/com/fivemybab/ittabab/group/command/dto/GroupCommentDTO.java
  src/main/java/com/fivemybab/ittabab/group/command/dto/GroupInfoDTO.java
  src/main/java/com/fivemybab/ittabab/group/command/dto/GroupMemberDTO.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupCategory.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupComment.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupInfo.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupMember.java
  src/main/java/com/fivemybab/ittabab/group/command/mapper/GroupMapper.java
  src/main/java/com/fivemybab/ittabab/group/query/Service/GroupQueryService.java
  src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupMapper.java
Labels: enhancement

#18 feat: member entity 구현
  src/main/java/com/fivemybab/ittabab/member/command/entity/BootCamp.java
  src/main/java/com/fivemybab/ittabab/member/command/entity/Course.java
  src/main/java/com/fivemybab/ittabab/member/command/entity/Friend.java
  src/main/java/com/fivemybab/ittabab/member/command/entity/MemberInfo.java
Labels: enhancement

#19 feat: good 도메인 엔티티 구현
  src/main/java/com/fivemybab/ittabab/good/command/entity/Good.java
Labels: enhancement

#17 feat: picture 도메인 엔티티 구현
  src/main/java/com/fivemybab/ittabab/picture/command/entity/Picture.java
Labels: enhancement

#22 feat: member 도메인 엔티티 구현
  src/main/java/com/fivemybab/ittabab/member/command/entity/Notification.java
Labels: enhancement

#23 fix: entity isBlinded 추가
  src/main/java/com/fivemybab/ittabab/board/command/entity/PostComment.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupComment.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupInfo.java
  src/main/java/com/fivemybab/ittabab/report/command/controller/ReportController.java
Labels: enhancement

#25 feat: entity 수정
  src/main/java/com/fivemybab/ittabab/member/command/dto/BootCampDTO.java
  src/main/java/com/fivemybab/ittabab/member/command/dto/CourseDTO.java
  src/main/java/com/fivemybab/ittabab/member/command/dto/FriendDTO.java
  src/main/java/com/fivemybab/ittabab/member/command/dto/MemberDTO.java
  src/main/java/com/fivemybab/ittabab/member/command/entity/MemberInfo.java
  src/main/java/com/fivemybab/ittabab/member/command/service/MemberCommandService.java
Labels: enhancement

#27 feat: 문의 관리
  src/main/java/com/fivemybab/ittabab/inquiry/command/controller/InquiryController.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/dto/InquiryDTO.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/entity/InquiryInfo.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/repository/InquiryRepository.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/service/InquiryService.java
Labels: enhancement

#24 fix: store entity 코드 컨벤션에 맞게 수정
  src/main/java/com/fivemybab/ittabab/store/command/entity/Favorite.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/Menu.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/MenuCategory.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/OrderMenu.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/Review.java
  src/main/java/com/fivemybab/ittabab/store/command/entity/Store.java
Labels: enhancement

#30 fix: report 수정 , memberInfo Getter 수정
  src/main/java/com/fivemybab/ittabab/member/command/entity/MemberInfo.java
  src/main/java/com/fivemybab/ittabab/report/command/service/ReportService.java
Labels: enhancement

#31 feat: Mybatis 설정 파일 추가
  build.gradle
  src/main/java/com/fivemybab/ittabab/config/MybatisConfig.java
  src/main/java/com/fivemybab/ittabab/group/command/controller/GroupController.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupCategory.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupComment.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupInfo.java
  src/main/java/com/fivemybab/ittabab/group/command/entity/GroupMember.java
  src/main/java/com/fivemybab/ittabab/group/command/mapper/GroupCommentMapper.java
  src/main/java/com/fivemybab/ittabab/group/command/mapper/GroupInfoMapper.java
  src/main/java/com/fivemybab/ittabab/group/command/mapper/GroupMapper.java
  src/main/java/com/fivemybab/ittabab/group/command/repository/GroupInfoRepository.java
  src/main/java/com/fivemybab/ittabab/group/command/service/GroupService.java
  src/main/resources/com/fivemybab/ittabab/group/command/mapper/GroupCommentMapper.xml
  src/main/resources/com/fivemybab/ittabab/group/command/mapper/GroupInfoMapper.xml
  src/main/resources/templates/group/detail.html
  src/main/resources/templates/group/list.html
  src/main/resources/templates/group/modify.html
Labels: enhancement

#35 feat: swagger 설정 추가
  build.gradle
  src/main/java/com/fivemybab/ittabab/config/SwaggerConfig.java
Labels: enhancement

#46 feat: 회원 가입 구현
  build.gradle
  src/main/java/com/fivemybab/ittabab/config/BeanConfig.java
  src/main/java/com/fivemybab/ittabab/report/command/repository/UserRepository.java
  src/main/java/com/fivemybab/ittabab/report/command/service/ReportService.java
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  src/main/java/com/fivemybab/ittabab/security/dto/ExceptionResponse.java
  src/main/java/com/fivemybab/ittabab/security/dto/LoginRequest.java
  src/main/java/com/fivemybab/ittabab/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/fivemybab/ittabab/security/filter/JwtFilter.java
  src/main/java/com/fivemybab/ittabab/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/fivemybab/ittabab/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/fivemybab/ittabab/security/handler/LoginFailureHandler.java
  src/main/java/com/fivemybab/ittabab/security/handler/LoginSuccessHandler.java
  src/main/java/com/fivemybab/ittabab/security/util/JwtUtil.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/BootCampDTO.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/CourseDTO.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/CreateUserRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/FriendDTO.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/UserDTO.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/UserRole.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/UserStatus.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/repository/UserRepository.java
  src/main/java/com/fivemybab/ittabab/user/command/repository/UserCommandRepository.java
  src/main/java/com/fivemybab/ittabab/user/command/service/UserCommandService.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/UserQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/UserMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/service/UserQueryService.java
  src/main/resources/application.yml
Labels: enhancement

#48 refactor: #42 일정 REST API로 변경
  src/main/java/com/fivemybab/ittabab/schedule/command/controller/ScheduleController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/domain/aggregate/ScheduleInfo.java
  src/main/java/com/fivemybab/ittabab/schedule/command/service/ScheduleService.java
Labels: enhancement

#49 feat: #47 기능 구현
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/BoardCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/service/BoardCommandService.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/repository/PostCommentRepository.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/repository/PostRepository.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/BoardQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/dto/BoardQueryDTO.java
  src/main/java/com/fivemybab/ittabab/board/query/mapper/BoardQueryMapper.java
  src/main/java/com/fivemybab/ittabab/board/query/service/BoardQueryService.java
Labels: enhancement

#53 refactor: #40 신고 RESTAPI 변경
  src/main/java/com/fivemybab/ittabab/report/command/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/command/dto/CreateReportDTO.java
  src/main/java/com/fivemybab/ittabab/report/command/service/ReportService.java
Labels: enhancement

#54 fix: 문의 RestController 수정
  src/main/java/com/fivemybab/ittabab/inquiry/command/controller/InquiryController.java
Labels: bug

#56 refactor: #55 Dto 이름 변경
  src/main/java/com/fivemybab/ittabab/board/query/dto/BoardQueryDto.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/dto/GroupCategoryDto.java
  src/main/java/com/fivemybab/ittabab/group/command/application/dto/GroupCommentDto.java
  src/main/java/com/fivemybab/ittabab/group/command/application/dto/GroupInfoDto.java
  src/main/java/com/fivemybab/ittabab/group/command/application/dto/GroupUserDto.java
  src/main/java/com/fivemybab/ittabab/group/command/application/mapper/GroupCommentMapper.java
  src/main/java/com/fivemybab/ittabab/group/command/application/mapper/GroupInfoMapper.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupService.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/controller/InquiryController.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/dto/InquiryDto.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/service/InquiryService.java
  src/main/java/com/fivemybab/ittabab/report/command/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/command/dto/CreateReportDto.java
  src/main/java/com/fivemybab/ittabab/report/command/dto/ReportDto.java
  src/main/java/com/fivemybab/ittabab/report/command/service/ReportService.java
  src/main/java/com/fivemybab/ittabab/schedule/command/controller/ScheduleController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/dto/ScheduleDto.java
  src/main/java/com/fivemybab/ittabab/schedule/command/service/ScheduleService.java
  src/main/java/com/fivemybab/ittabab/store/command/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/FavoriteDto.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/MenuCategoryDto.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/MenuDto.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/OrderMenuDto.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/ReviewDto.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/StoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/UserQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/dto/UserDto.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/UserMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/service/UserQueryService.java
  src/main/resources/mapper/group/GroupCommentMapper.xml
  src/main/resources/mapper/group/GroupInfoMapper.xml
  src/test/java/com/fivemybab/ittabab/group/command/application/service/GroupServiceTest.java
Labels: enhancement

#58 feat: group 채팅 기능 수정
  build.gradle
  src/main/java/com/fivemybab/ittabab/config/WebSocketConfig.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/dto/ChatMessageDto.java
  src/main/java/com/fivemybab/ittabab/group/command/application/dto/GroupCommentDto.java
  src/main/java/com/fivemybab/ittabab/group/command/application/handler/ChatHandler.java
  src/main/java/com/fivemybab/ittabab/group/command/application/handler/WebSocketChatHandler.java
  src/main/resources/templates/group/chatroom.html
  src/main/resources/templates/group/chatting.html
Labels: enhancement

#60 feat: 회원 정보 수정 기능 구현
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/UpdateUserRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/UserDto.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/UserQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/UserMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/service/UserQueryService.java
Labels: enhancement

#63 feat: #61 회원 삭제 기능 구현
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/UserInfo.java
Labels: enhancement

#62 feat: board jpa구현
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/BoardCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/dto/CreateBoardDTO.java
  src/main/java/com/fivemybab/ittabab/board/command/application/dto/UpdatedBoardDTO.java
  src/main/java/com/fivemybab/ittabab/board/command/application/service/BoardCommandService.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/aggregate/Post.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/repository/PostCommentRepository.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/repository/PostRepository.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/BoardQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/service/BoardQueryService.java
  src/main/resources/mapper/board/BoardMapper.xml
Labels: enhancement

#74 refactor: #66 신고 CQRS패턴으로 변경
  src/main/java/com/fivemybab/ittabab/report/command/application/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/command/application/dto/CreateReportResponse.java
  src/main/java/com/fivemybab/ittabab/report/command/application/dto/ResolveReportRequest.java
  src/main/java/com/fivemybab/ittabab/report/command/application/dto/ResolveReportResponse.java
  src/main/java/com/fivemybab/ittabab/report/command/application/service/ReportService.java
  src/main/java/com/fivemybab/ittabab/report/command/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/command/domain/repository/ReportRepository.java
  src/main/java/com/fivemybab/ittabab/report/command/service/ReportService.java
  src/main/java/com/fivemybab/ittabab/report/query/controller/ReportQueryController.java
  src/main/java/com/fivemybab/ittabab/report/query/dto/ReportDto.java
  src/main/java/com/fivemybab/ittabab/report/query/mapper/ReportMapper.java
  src/main/java/com/fivemybab/ittabab/report/query/service/ReportQueryService.java
  src/main/resources/mapper/report/ReportMapper.xml
Labels: enhancement

#76 fix: 디렉토리 구조 수정
  src/main/java/com/fivemybab/ittabab/bootcamp/command/dto/BootCampDTO.java
  src/main/java/com/fivemybab/ittabab/bootcamp/command/mapper/BootCampMapper.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/BootCampCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/BootCampService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/BootCamp.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/repository/BootCampRepository.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/BootCampMapper.java
  src/main/resources/mapper/user/BootCampMapper.xml
Labels: fix

#77 fix: session을 mapper 수정
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/mapper/GroupInfoMapper.java
  src/main/java/com/fivemybab/ittabab/group/command/application/mapper/GroupUserMapper.java
  src/main/java/com/fivemybab/ittabab/group/command/application/repository/GroupInfoRepository.java
  src/main/java/com/fivemybab/ittabab/group/command/application/repository/GroupUserRepository.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupService.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/GroupCategory.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/GroupComment.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/GroupInfo.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/GroupUser.java
  src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupMapper.java
  src/main/resources/mapper/group/GroupInfoMapper.xml
  src/main/resources/mapper/group/GroupUserMapper.xml
  src/test/java/com/fivemybab/ittabab/group/command/application/controller/GroupControllerTest.java
  src/test/java/com/fivemybab/ittabab/group/command/application/service/GroupServiceTest.java
Labels: fix

#79 fix: group 디렉토리 cqrs 패턴 구조로 변경 + 엔티티 오류 수정
  src/main/java/com/fivemybab/ittabab/config/WebSocketConfig.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/handler/ChatHandler.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupService.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/GroupCategory.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/GroupComment.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/repository/GroupInfoRepository.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/repository/GroupUserRepository.java
  src/main/java/com/fivemybab/ittabab/group/command/infrastructure/handler/WebSocketChatHandler.java
  src/main/java/com/fivemybab/ittabab/group/query/Service/GroupQueryService.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupQueryController.java
  src/main/java/com/fivemybab/ittabab/group/query/dto/ChatMessageDto.java
  src/main/java/com/fivemybab/ittabab/group/query/dto/GroupCategoryDto.java
  src/main/java/com/fivemybab/ittabab/group/query/dto/GroupCommentDto.java
  src/main/java/com/fivemybab/ittabab/group/query/dto/GroupInfoDto.java
  src/main/java/com/fivemybab/ittabab/group/query/dto/GroupUserDto.java
  src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupCommentMapper.java
  src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupInfoMapper.java
  src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupUserMapper.java
  src/main/resources/mapper/group/GroupCommentMapper.xml
  src/main/resources/mapper/group/GroupInfoMapper.xml
  src/main/resources/mapper/group/GroupUserMapper.xml
  src/test/java/com/fivemybab/ittabab/group/command/application/service/GroupServiceTest.java
Labels: fix

#82 refactor: 일정 CQRS패턴으로 변경, restful하게 변경
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/controller/InquiryController.java
  src/main/java/com/fivemybab/ittabab/inquiry/query/controller/InquiryQueryController.java
  src/main/java/com/fivemybab/ittabab/report/command/application/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/command/application/dto/CreateReportRequest.java
  src/main/java/com/fivemybab/ittabab/report/command/application/service/ReportService.java
  src/main/java/com/fivemybab/ittabab/report/query/controller/ReportQueryController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/controller/ScheduleController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/dto/ScheduleDto.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/dto/ScheduleModifyRequest.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/service/ScheduleService.java
  src/main/java/com/fivemybab/ittabab/schedule/command/controller/ScheduleController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/domain/repository/ScheduleRepository.java
  src/main/java/com/fivemybab/ittabab/schedule/query/controller/ScheduleQueryController.java
  src/main/java/com/fivemybab/ittabab/schedule/query/mapper/ScheduleMapper.java
  src/main/java/com/fivemybab/ittabab/schedule/query/service/ScheduleQueryService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/repository/UserRepository.java
  src/main/resources/mapper/schedule/ScheduleMapper.xml
Labels: refactor

#83 feat: store 및 review CRUD 구현
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/FavoriteDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/MenuCategoryDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/MenuDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/OrderMenuDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreInfoDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreRegistDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreReviewInfoDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreReviewRegistDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreReviewUpdateDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreStatus.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreUpdateDTO.java
  src/main/java/com/fivemybab/ittabab/store/command/application/mapper/ReviewInfoMapper.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreReviewRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreReviewService.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/command/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/Store.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/StoreReview.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/MenuCategoryDto.java
  src/main/java/com/fivemybab/ittabab/store/command/dto/StoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreReviewMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreQueryService.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreReviewQueryService.java
  src/main/resources/application.yml
  src/main/resources/mapper/store/StoreMapper.xml
  src/main/resources/mapper/store/StoreReviewMapper.xml
Labels: enhancement

#84 refactor: #78 bootcamp 관련 리팩토링
  src/main/java/com/fivemybab/ittabab/exception/NotFoundException.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/BootCampCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/CreateBootCampRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/UpdateBootCampRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/BootCampCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/BootCampService.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/BootCamp.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/BootCampQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/UserQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/dto/BootCampDto.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/BootCampMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/service/BootCampQueryService.java
  src/main/resources/mapper/user/BootCampMapper.xml
Labels: refactor

#86 feat: loginId를 userId로 변환 메소드 구현
  src/main/java/com/fivemybab/ittabab/user/query/mapper/UserMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/service/UserQueryService.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: enhancement

#88 fix: storeDto 클래스명 코드 컨벤션에 맞게 수정
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreReviewDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreInfoDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreReviewInfoDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/UpdateStoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/UpdateStoreReviewDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/mapper/ReviewInfoMapper.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreReviewService.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreReviewMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreQueryService.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreReviewQueryService.java
  src/main/resources/mapper/store/StoreMapper.xml
  src/main/resources/mapper/store/StoreReviewMapper.xml
Labels: enhancement

#91 feature: 좋아요 기능 구현
  src/main/java/com/fivemybab/ittabab/good/command/application/controller/GoodController.java
  src/main/java/com/fivemybab/ittabab/good/command/application/dto/GoodRequestDto.java
  src/main/java/com/fivemybab/ittabab/good/command/application/service/GoodService.java
  src/main/java/com/fivemybab/ittabab/good/command/domain/aggregate/Good.java
  src/main/java/com/fivemybab/ittabab/good/command/domain/repository/GoodRepository.java
Labels: enhancement

#93 fix: 유저 도메인 스웨거 관련 어노테이션 추가
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/UserQueryController.java
Labels: fix

#95 refactor: #90 좋아요 조회 기능 리팩토링
  src/main/java/com/fivemybab/ittabab/good/command/application/controller/GoodCommandController.java
  src/main/java/com/fivemybab/ittabab/good/command/application/controller/GoodController.java
  src/main/java/com/fivemybab/ittabab/good/command/application/service/GoodCommandService.java
  src/main/java/com/fivemybab/ittabab/good/command/domain/aggregate/Good.java
  src/main/java/com/fivemybab/ittabab/good/command/domain/repository/GoodRepository.java
  src/main/java/com/fivemybab/ittabab/good/query/controller/GoodQueryController.java
  src/main/java/com/fivemybab/ittabab/good/query/dto/CountGoodRequest.java
  src/main/java/com/fivemybab/ittabab/good/query/mapper/GoodMapper.java
  src/main/java/com/fivemybab/ittabab/good/query/service/GoodQueryService.java
  src/main/resources/mapper/good/GoodMapper.xml
Labels: refactor

#97 refactor: #96 command 파일명 변경
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/controller/InquiryCommandController.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/service/InquiryCommandService.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/controller/ScheduleCommandController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/service/ScheduleCommandService.java
Labels: refactor

#98 feat: 즐겨찾기 기능 구현 및 코드 리팩토링
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreFavoriteController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreMenuController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreReviewController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreFavoriteDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreFavoriteInfoDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreFavoriteRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreFavoriteService.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreReviewService.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/StoreFavorite.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/StoreReview.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreFavoriteQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreFavoriteMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreFavoriteQueryService.java
  src/main/resources/mapper/store/StoreFavoriteMapper.xml
Labels: enhancement

#99 feat: board 완성
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/BoardCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/service/BoardCommandService.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/aggregate/Post.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/BoardCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/BoardQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/dto/BoardCommentQueryDto.java
  src/main/java/com/fivemybab/ittabab/board/query/dto/BoardQueryDto.java
  src/main/java/com/fivemybab/ittabab/board/query/mapper/BoardCommentQueryMapper.java
  src/main/java/com/fivemybab/ittabab/board/query/mapper/BoardQueryMapper.java
  src/main/java/com/fivemybab/ittabab/board/query/service/BoardCommentQueryService.java
  src/main/java/com/fivemybab/ittabab/board/query/service/BoardQueryService.java
  src/main/resources/mapper/board/BoardCommentMapper.xml
  src/main/resources/mapper/board/BoardMapper.xml
Labels: enhancement

#100 refactor: Controller Swagger Tag 추가
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreFavoriteController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreMenuController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreReviewController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreFavoriteQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreMenuQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreReviewQueryController.java
Labels: refactor

#101 refactor: Controller 메소드 @operation 설명 추가
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreFavoriteController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreMenuController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreReviewController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreFavoriteQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreMenuQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreReviewQueryController.java
Labels: refactor

#103 feat: #102 친구 기능 구현
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/FriendCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/FriendRequestDTO.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/UpdateFriendRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/FriendCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/Friend.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/FriendStatus.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/repository/FriendRepository.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/FriendQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/FriendMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/service/FriendQueryService.java
  src/main/resources/mapper/user/FriendMapper.xml
Labels: enhancement

#104 fix: user 조회 일부 수정
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/BootCampQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/UserMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/service/UserQueryService.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: fix

#108 feat: course 관련 기능 구현
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/CourseCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/CreateCourseRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/UpdateCourseRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/CourseCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/Course.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/repository/CourseRepository.java
  src/main/java/com/fivemybab/ittabab/user/query/controller/CourseQueryController.java
  src/main/java/com/fivemybab/ittabab/user/query/dto/CourseDto.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/CourseMapper.java
  src/main/java/com/fivemybab/ittabab/user/query/service/CourseQueryService.java
  src/main/resources/mapper/user/CourseMapper.xml
Labels: enhancement

#107 feat: 사진 기능 구현
  src/main/java/com/fivemybab/ittabab/picture/command/application/controller/PictureCommandController.java
  src/main/java/com/fivemybab/ittabab/picture/command/application/service/PictureCommandService.java
  src/main/java/com/fivemybab/ittabab/picture/command/domain/aggregate/Picture.java
  src/main/java/com/fivemybab/ittabab/picture/command/domain/repository/PictureRepository.java
  src/main/resources/application.yml
Labels: enhancement

#111 fix: picture 요청 데이터 형식 지정
  src/main/java/com/fivemybab/ittabab/picture/command/application/controller/PictureCommandController.java
  src/main/java/com/fivemybab/ittabab/picture/command/application/service/PictureCommandService.java
Labels: fix

#112 fix: swagger 설정
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/BoardCommandController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/BoardCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/BoardQueryController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupController.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupQueryController.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/controller/InquiryCommandController.java
  src/main/java/com/fivemybab/ittabab/inquiry/query/controller/InquiryQueryController.java
  src/main/java/com/fivemybab/ittabab/report/command/application/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/query/controller/ReportQueryController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/controller/ScheduleCommandController.java
  src/main/java/com/fivemybab/ittabab/schedule/query/controller/ScheduleQueryController.java
Labels: refactor

#114 refactor: 반환 타입을 ResponseEntity<> 타입으로 변경
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupQueryController.java
  src/main/resources/mapper/group/GroupInfoMapper.xml
Labels: refactor

#116 refactor: Swagger 태그 추가
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/BoardCommandController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/BoardCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/BoardQueryController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupService.java
  src/main/java/com/fivemybab/ittabab/group/query/Service/GroupQueryService.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupQueryController.java
  src/main/java/com/fivemybab/ittabab/inquiry/command/application/controller/InquiryCommandController.java
  src/main/java/com/fivemybab/ittabab/inquiry/query/controller/InquiryQueryController.java
  src/main/java/com/fivemybab/ittabab/picture/command/application/controller/PictureCommandController.java
  src/main/java/com/fivemybab/ittabab/report/command/application/controller/ReportController.java
  src/main/java/com/fivemybab/ittabab/report/query/controller/ReportQueryController.java
  src/main/java/com/fivemybab/ittabab/schedule/command/application/controller/ScheduleCommandController.java
  src/main/java/com/fivemybab/ittabab/schedule/query/controller/ScheduleQueryController.java
Labels: refactor

#109 feat: board post comment cud
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/BoardCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/dto/CreatePostCommentDto.java
  src/main/java/com/fivemybab/ittabab/board/command/application/dto/CreatePostDto.java
  src/main/java/com/fivemybab/ittabab/board/command/application/dto/UpdatePostCommentDto.java
  src/main/java/com/fivemybab/ittabab/board/command/application/dto/UpdatedPostDto.java
  src/main/java/com/fivemybab/ittabab/board/command/application/service/PostCommandService.java
  src/main/java/com/fivemybab/ittabab/board/command/application/service/PostCommentCommandService.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/aggregate/PostComment.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/repository/PostCommentRepository.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/dto/PostCommentQueryDto.java
  src/main/java/com/fivemybab/ittabab/board/query/dto/PostQueryDto.java
  src/main/java/com/fivemybab/ittabab/board/query/mapper/PostCommentQueryMapper.java
  src/main/java/com/fivemybab/ittabab/board/query/mapper/PostQueryMapper.java
  src/main/java/com/fivemybab/ittabab/board/query/service/PostCommentQueryService.java
  src/main/java/com/fivemybab/ittabab/board/query/service/PostQueryService.java
  src/main/resources/mapper/board/PostCommentMapper.xml
  src/main/resources/mapper/board/PostMapper.xml
Labels: enhancement

#117 feat: 알림 기능 구현
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/NotificationCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/CreateNotificationRequest.java
  src/main/java/com/fivemybab/ittabab/user/command/application/dto/NotificationDto.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/NotificationCommandService.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/Notification.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/repository/NotificationRepository.java
Labels: enhancement

#123 feat: 모임 댓글 게시판 개발
  http/security-test.http
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupInfoCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandService.java
  src/main/java/com/fivemybab/ittabab/group/query/Service/GroupInfoQueryService.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupInfoQueryController.java
  src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupInfoMapper.java
  src/main/resources/mapper/group/GroupInfoMapper.xml
  src/test/java/com/fivemybab/ittabab/group/command/application/controller/GroupControllerTest.java
  src/test/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandServiceTest.java
Labels: enhancement

#124 fix: service 디렉토리 소문자 변경
  src/main/java/com/fivemybab/ittabab/group/query/service/GroupInfoQueryService.java
Labels: fix

#120 feat: 주문메뉴 기능 구현
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreOrderMenuController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreOrderMenuDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/StoreOrderMenuInfoDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/repository/StoreOrderMenuRepository.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreOrderMenuService.java
  src/main/java/com/fivemybab/ittabab/store/command/domain/aggregate/StoreOrderMenu.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreOrderMenuQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreOrderMenuMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreOrderMenuQueryService.java
  src/main/resources/mapper/store/StoreOrderMenuMapper.xml
Labels: enhancement

#125 fix: board 일부 수정
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/BoardCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/service/PostCommentCommandService.java
  src/main/java/com/fivemybab/ittabab/board/command/domain/aggregate/PostComment.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostQueryController.java
Labels: enhancement

#128 fix: #127 spring security 수정
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  src/main/java/com/fivemybab/ittabab/security/handler/LoginSuccessHandler.java
  src/main/java/com/fivemybab/ittabab/security/util/JwtUtil.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/domain/aggregate/UserInfo.java
  src/main/java/com/fivemybab/ittabab/user/query/mapper/UserMapper.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: fix

#122 feat: 회원 command 테스트 코드 추가
  src/test/java/com/fivemybab/ittabab/user/command/application/service/UserCommandServiceTest.java
Labels: enhancement

#126 fix: board 수정사항 반영
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommandController.java
  src/main/java/com/fivemybab/ittabab/board/command/application/controller/PostCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/board/query/controller/PostQueryController.java
Labels: fix

#129 feat: 가게 command 및 query 테스트 코드 추가
  src/main/java/com/fivemybab/ittabab/store/command/application/controller/StoreController.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/CreateStoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/dto/UpdateStoreDto.java
  src/main/java/com/fivemybab/ittabab/store/command/application/service/StoreService.java
  src/main/java/com/fivemybab/ittabab/store/query/controller/StoreMenuQueryController.java
  src/main/java/com/fivemybab/ittabab/store/query/mapper/StoreMenuMapper.java
  src/main/java/com/fivemybab/ittabab/store/query/service/StoreMenuQueryService.java
  src/main/resources/mapper/store/StoreMenuMapper.xml
  src/test/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuServiceTest.java
  src/test/java/com/fivemybab/ittabab/store/command/application/service/StoreServiceTest.java
  src/test/java/com/fivemybab/ittabab/store/query/service/StoreMenuQueryServiceTest.java
  src/test/java/com/fivemybab/ittabab/store/query/service/StoreQueryServiceTest.java
Labels: enhancement

#131 feat: 가게 메뉴 테스트 코드 작성
  src/test/java/com/fivemybab/ittabab/store/command/application/service/StoreMenuServiceTest.java
Labels: enhancement, refactor

#130 feat: 모임 댓글 기능 개발
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupCommentCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/controller/GroupInfoCommandController.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupCommentCommandService.java
  src/main/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandService.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/aggregate/GroupComment.java
  src/main/java/com/fivemybab/ittabab/group/command/domain/repository/GroupCommentRepository.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupCommentQueryController.java
  src/main/java/com/fivemybab/ittabab/group/query/controller/GroupInfoQueryController.java
  src/main/java/com/fivemybab/ittabab/group/query/dto/UpdateGroupCommentDto.java
  src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupCommentMapper.java
  src/main/java/com/fivemybab/ittabab/group/query/mapper/GroupInfoMapper.java
  src/main/java/com/fivemybab/ittabab/group/query/service/GroupCommentQueryService.java
  src/main/java/com/fivemybab/ittabab/group/query/service/GroupInfoQueryService.java
  src/main/resources/mapper/group/GroupCommentMapper.xml
  src/main/resources/mapper/group/GroupInfoMapper.xml
  src/test/java/com/fivemybab/ittabab/group/command/application/service/GroupInfoCommandServiceTest.java
  src/test/java/com/fivemybab/ittabab/group/query/service/GroupCommentQueryServiceTest.java
  src/test/java/com/fivemybab/ittabab/group/query/service/GroupInfoQueryServiceTest.java
Labels: enhancement

#133 fix: security 수정
  src/main/java/com/fivemybab/ittabab/security/config/SecurityConfig.java
  src/main/java/com/fivemybab/ittabab/security/util/CustomUserDetails.java
  src/main/java/com/fivemybab/ittabab/security/util/CustomUserDetailsService.java
  src/main/java/com/fivemybab/ittabab/security/util/JwtUtil.java
  src/main/java/com/fivemybab/ittabab/user/command/application/controller/UserCommandController.java
  src/main/java/com/fivemybab/ittabab/user/command/application/service/UserCommandService.java
Labels: fix
